apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  FLASK_DB_USER: cG9zdGdyZXM=    
  FLASK_DB_PASSWORD: c2VjcmV0cGFzcw==    
  POSTGRES_USER: cG9zdGdyZXM=    
  POSTGRES_PASSWORD: c2VjcmV0cGFzcw==   
